### PR TITLE
Responsive image update, one image for each breakpoint 

### PR DESCRIPTION
**Pull request by denisjacquemin**
Hi Ben,

I suggest the following update for managing responsive images:

metaQuery add `src` attribute to the `` elements by adding the breakpoint-name at the end of the filename

One image file for each breakpoint has to be defined, following the naming convention 

``` html
<name>-<name-of-breakpoint>.<extension>
```

ie:

```
moon-phone.jpg
moon-tablet.jpg
```

### CODE REVIEW

**Comment by benschwarz** [comment]
Great stuff Denis. 
To be clear—You're doing this to save on having to redefine the pattern on every single image tag?

**Comment by denisjacquemin** [comment]
Just realised that I misunderstood your example in the README

I thought you were always replacing the whole filename with the breakpoint, which leads to only one responsive image per page

so the main goal of the pull request was to allow any number of images in the same page.

at the end, my pull request is a small win, allow to avoid the [breakpoint] in the markup

also, I think it's worth mentioning that having an initial src value, can result with an extra useless http request, it can be left blank because metaQuery take care of it

Cheers

**Comment by benschwarz** [comment]
Old school tells me "but what about the guys without JavaScript", but reality tells me forget it, omit src if you feel like it. 

I kinda like the template option because it allows non metaquery images to live as normal…

**Comment by denisjacquemin** [comment]
obviously, my pull request doesn't bring any real added value to metaQuery, was a good exercise anyway

**Comment by benschwarz** [comment]
No worries Denis, your involvement and review has been really valuable. 

Cheers :-)

**Pull request closed without merging**
