### PR TITLE
Allow passing of active breakpoints into the onBreakpointChange callback

### PR DESCRIPTION
**Pull request by plasticine**
Does pretty much what it says on the can...

The use-case for this is to allow for programatically taking action when a mediaquery changes, and having a reference for which breakpoints are actually active at the time of the event being triggered.

This is cool because it would allow you to have your client-side app code to consume and respond to the current breakpoint, for example by redrawing the UI using a system like React.

---
### TODOs
- [x] Add example
- [x] Minify
- [x] Update README.

---

untitled mov

### CODE REVIEW

**Comment by plasticine** [comment]
@benschwarz do you want me to update the README on this one or is that something you would prefer to do?

**Comment by plasticine** [comment]
Also, Travis seems to be having a bad time with PhantomJS at the moment — can run specs locally OK though :/

**Comment by benschwarz** [comment]
If you could update the `README.md` also, that would be incredible :heart_eyes: 
As for travis, not sure whats going on there :-1:

**Comment by plasticine** [comment]
> If you could update the README.md also, that would be incredible

Cool — will do.

**Comment by benschwarz** [comment]
LGTM. Thanks @plasticine ! :bird:

**Pull request merged**
