### PR TITLE
npm package?

### PR DESCRIPTION
**Pull request by plasticine**
Would this be something that you would consider, @benschwarz?

I realise that the JS package manager situation is pretty LOLed, but not being able to consume metaquery via `npm` is pretty frustrating.

### CODE REVIEW

**Comment by levibuzolic** [comment]
Having this available on NPM would be :star:

**Comment by plasticine** [comment]
I’ve updated this issue with a minimal update to the existing `package.json`, with an update version field and reformatted author field.

**Comment by benschwarz** [comment]
https://www.npmjs.org/package/metaquery

**Comment by plasticine** [comment]
:heart:

**Pull request merged**
