### PR TITLE
reverting back to window.module. Tests are passing.

### PR DESCRIPTION
**Pull request by jdeblank**

### CODE REVIEW

**Comment by jdeblank** [comment]
Hopefully fixes #27

**Comment by benschwarz** [comment]
Ergh. What a pain in the ass! 
I'll review and figure out what to do next…

**Comment by benschwarz** [comment]
I didn't do a very good job of tracking this one through :facepunch: 
Sorry @jdeblank !

**Comment by jdeblank** [comment]
All good mate. From memory, you ended up writing a more CommonJS solution, which made more sense. :+1:

**Pull request closed without merging**
