### PR TITLE
Multiple breakpoints

### PR DESCRIPTION
**Pull request by CaseyLeask**
Now with jQuery support!

### CODE REVIEW

**Comment by benschwarz** [comment]
To be clear: When the multiple breakpoints are matched, multiple classes will be applied to the `<html>` element?
What happens for the element/image templating options?  Which name will be used?

**Comment by CaseyLeask** [comment]
In the situation of multiple matching breakpoints;
- all the classes that apply are added to `<html>` element.
- `` tags with the ```data-mq-src` attribute will have the all the names concatenated with '-'.

For the `html` element;

``` html
    <meta name="breakpoint" content="widescreen" media="(min-width: 1024px)">
    <meta name="breakpoint" content="retina" media="only screen and (-moz-min-device-pixel-ratio: 1.25), only screen and (-o-min-device-pixel-ratio: 2.5/2), only screen and (-webkit-min-device-pixel-ratio: 1.25), only screen  and (min-device-pixel-ratio: 1.25), only screen and (min-resolution: 1.25dppx)">
```

gives me

``` html
<html class="breakpoint-widescreen breakpoint-retina">
```

For the `` tag;

``` html
    <img alt="moon" data-mq-src="./moon-[breakpoint].jpg">
```

gives

``` html
    <img alt="moon" data-mq-src="./moon-[breakpoint].jpg" src="./moon-widescreen-retina.jpg">
```

**Comment by benschwarz** [comment]
So presumably the template string ordering is based on order of occurrence (as defined by the meta tags)? 
Probably worth adding a test for that one…

**Comment by CaseyLeask** [comment]
Since an object is an unordered collection of properties, I need to rewrite this in something that respects order.

**Pull request closed without merging**
